# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'mail', '~> 2.8'
gem 'rack-cors', '~> 2.0'
gem 'json', '~> 2.7'
